# fly.toml app configuration file generated for relivator on 2024-03-25T17:48:15+01:00
# See https://fly.io/docs/reference/configuration for information about how to use it.

app = "relivator"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 10000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# [build]
#   builder = "paketobuildpacks/builder:base"

# [env]
#   PORT = "10000"

# [http_service]
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0

# [[vm]]
#   memory = "1gb"
#   cpu_kind = "shared"
#   cpus = 1
